import localFont from "next/font/local";
import "./globals.css";

// Importing Erode font
const erode = localFont({
  src: [
    {
      path: '../../public/font/Erode-Variable.ttf',
      weight: '300',
    },
    {
      path: '../../public/font/Erode-Variable.ttf',
      weight: '400',
    },
    {
      path: '../../public/font/Erode-Variable.ttf',
      weight: '500',
    },
    {
      path: '../../public/font/Erode-Variable.ttf',
      weight: '600',
    },
    {
      path: '../../public/font/Erode-Variable.ttf',
      weight: '700',
    },
  ],
  variable: '--font-erode',
});

// Importing Satoshi font
const satoshi = localFont({
  src: [
    {
      path: '../../public/font/Satoshi-Variable.ttf',
      weight: '300',
    },
    {
      path: '../../public/font/Satoshi-Variable.ttf',
      weight: '400',
    },
    {
      path: '../../public/font/Satoshi-Variable.ttf',
      weight: '500',
    },
    {
      path: '../../public/font/Satoshi-Variable.ttf',
      weight: '600',
    },
    {
      path: '../../public/font/Satoshi-Variable.ttf',
      weight: '700',
    },
  ],
  variable: '--font-satoshi',
});

const metadata = {
  title: "Ullsta Gård",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#FFFDFA]">{children}</body>
    </html>
  );
}
